<?php
/**
 * Created by PhpStorm.
 * User: changhe
 * Date: 2017/4/25
 * Time: 20:54
 */

namespace HuicuiApi\Handler;


use HuicuiApi\Exception\HuicuiApiApapterException;

class MemcachedAdapter extends HandlerAdapter implements HandlerInterface
{
    /**
     * @return \Memcached
     */
    public function getAdapter()
    {
        return parent::getAdapter(); // TODO: Change the autogenerated stub
    }

    /**
     * @param \Memcached $adapter
     *
     * @throws HuicuiApiApapterException
     */
    public function setAdapter($adapter)
    {
        if(!$adapter || !is_object($adapter)){
            throw new HuicuiApiApapterException("adapter 必须为 Redis 等类");
        }
        parent::setAdapter($adapter); // TODO: Change the autogenerated stub
    }

    function get($key)
    {
        return $this->getAdapter()->get($key);
    }

    /**
     * 设置一个 Memcached 的类型的可过期值
     * @param     $key
     * @param     $val
     * @param int $expire
     *
     * @return bool
     */
    function set($key, $val, $expire = 7100)
    {
        return $this->getAdapter()->set($key,$val,$expire);
    }
}