<?php
/**
 * Created by PhpStorm.
 * User: changhe
 * Date: 2017/4/25
 * Time: 20:54
 */

namespace HuicuiApi\Handler;


use HuicuiApi\Exception\HuicuiApiApapterException;

class RedisAdapter extends HandlerAdapter implements HandlerInterface
{
    /**
     * @return \Redis
     */
    public function getAdapter()
    {
        return parent::getAdapter(); // TODO: Change the autogenerated stub
    }

    /**
     * @param \Redis $adapter
     *
     * @throws HuicuiApiApapterException
     */
    public function setAdapter(\Redis $adapter)
    {
        if(!$adapter || $adapter instanceof \Redis){
            throw new HuicuiApiApapterException("adapter 必须为 Redis 类");
        }
        parent::setAdapter($adapter); // TODO: Change the autogenerated stub
    }

    function get($key)
    {
        return $this->getAdapter()->get($key);
    }

    /**
     * 设置一个 redis 的类型的可过期值
     * @param     $key
     * @param     $val
     * @param int $expire
     *
     * @return bool
     */
    function set($key, $val, $expire = 7100)
    {
        return $this->getAdapter()->setex($key,$expire,$val);
    }
}